name: Docker Image CI

on:
  push:
    branches:    
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Github Packages
      run: docker login docker.pkg.github.com --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.GITHUB_BUILDER }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_BUILDER_TOKEN }}
    - name: Build Ruby 2.7.0
      run: make RUBY_MAJOR=2 RUBY_MINOR=7 RUBY_PATCH=0 ci
    - name: Build Ruby 2.6.5
      run: make RUBY_MAJIR=2 RUBY_MINOR=6 RUBY_PATCH=5 ci

